# Site settings
title: GitBucket News
#email: your-email@domain.com
description: "GitBucket is a Git platform powered by Scala."
url: "https://gitbucket.github.io"
baseurl: "/gitbucket-news"

# Build settings
markdown: kramdown
#permalink: prettay

paginate: 10

kramdown:
  input: GFM
  hard_wrap: false

logo: /favicon.png

gems:
  - jekyll-paginate
  - jemoji
#  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
